### ISSUE TITLE
Only getting 1 second of recording

### ISSUE THREAD

**Issue by cmosguy** [Ryan-Rudes/colabgymrender#6]
When I attempt to record an environment, it only records 1 second worth of video.  What am I doing wrong?

```python
import gym

env = gym.make("LunarLander-v2")
env.action_space.seed(42)

env = Recorder(env, './video')

observatio = env.reset()

# img = plt.imshow(env.render('rgb_array'))

observation = env.reset()
for _ in range(10000):
  # img.set_data(env.render('rgb_array'))
  # display.display(plt.gcf())
  # display.clear_output(wait=True)
  observation, reward, done, info = env.step(env.action_space.sample())

  if done:
      observation = env.reset()

env.release()
env.play()
env.close()
```

**Comment by ryanrudes** [comment]
Take a look at the source code. When you call `env.reset()`, recording restarts, so what seems to be happening is you have some termination around iteration 9900 or so. From there, you call env.reset(), and the final video is only the last episode (or whatever has been made of it so far). I think you are under the assumption that videos are concatenated after `env.reset()`, which is not true. Instead, recording resets and begins a new video on `env.reset()`.

Try this instead:

```python
import gym
from colabgymrender import Recorder

env = gym.make("LunarLander-v2")
env.action_space.seed(42)

env = Recorder(env, './video')

observation = env.reset()

for _ in range(10000):
    observation, reward, done, info = env.step(env.action_space.sample())

    if done:
        env.release()
        env.play()
        observation = env.reset()

env.close()
```

**Comment by cmosguy** [comment]
@ryanrudes Apologies and thank you for your clarification. This all makes sense!
